/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.thebes.common.thrift;

import org.apache.thrift.TException;

public class TTransactionAbortedException extends TException {
    private static final long serialVersionUID = -4769338889351502162L;
    private final String errorMessage;
    
    public TTransactionAbortedException(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getErrorMessage() {
        return errorMessage;
    }
}