/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yahoo.ycsb.db.tpcc.helper.rows;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HistoryRow implements org.apache.thrift.TBase<HistoryRow, HistoryRow._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HistoryRow");

  private static final org.apache.thrift.protocol.TField H_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("h_amount", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField H_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("h_data", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HistoryRowStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HistoryRowTupleSchemeFactory());
  }

  public double h_amount; // required
  public String h_data; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    H_AMOUNT((short)1, "h_amount"),
    H_DATA((short)2, "h_data");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // H_AMOUNT
          return H_AMOUNT;
        case 2: // H_DATA
          return H_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __H_AMOUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.H_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("h_amount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.H_DATA, new org.apache.thrift.meta_data.FieldMetaData("h_data", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HistoryRow.class, metaDataMap);
  }

  public HistoryRow() {
  }

  public HistoryRow(
    double h_amount,
    String h_data)
  {
    this();
    this.h_amount = h_amount;
    setH_amountIsSet(true);
    this.h_data = h_data;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HistoryRow(HistoryRow other) {
    __isset_bitfield = other.__isset_bitfield;
    this.h_amount = other.h_amount;
    if (other.isSetH_data()) {
      this.h_data = other.h_data;
    }
  }

  public HistoryRow deepCopy() {
    return new HistoryRow(this);
  }

  @Override
  public void clear() {
    setH_amountIsSet(false);
    this.h_amount = 0.0;
    this.h_data = null;
  }

  public double getH_amount() {
    return this.h_amount;
  }

  public HistoryRow setH_amount(double h_amount) {
    this.h_amount = h_amount;
    setH_amountIsSet(true);
    return this;
  }

  public void unsetH_amount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __H_AMOUNT_ISSET_ID);
  }

  /** Returns true if field h_amount is set (has been assigned a value) and false otherwise */
  public boolean isSetH_amount() {
    return EncodingUtils.testBit(__isset_bitfield, __H_AMOUNT_ISSET_ID);
  }

  public void setH_amountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __H_AMOUNT_ISSET_ID, value);
  }

  public String getH_data() {
    return this.h_data;
  }

  public HistoryRow setH_data(String h_data) {
    this.h_data = h_data;
    return this;
  }

  public void unsetH_data() {
    this.h_data = null;
  }

  /** Returns true if field h_data is set (has been assigned a value) and false otherwise */
  public boolean isSetH_data() {
    return this.h_data != null;
  }

  public void setH_dataIsSet(boolean value) {
    if (!value) {
      this.h_data = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case H_AMOUNT:
      if (value == null) {
        unsetH_amount();
      } else {
        setH_amount((Double)value);
      }
      break;

    case H_DATA:
      if (value == null) {
        unsetH_data();
      } else {
        setH_data((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case H_AMOUNT:
      return Double.valueOf(getH_amount());

    case H_DATA:
      return getH_data();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case H_AMOUNT:
      return isSetH_amount();
    case H_DATA:
      return isSetH_data();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HistoryRow)
      return this.equals((HistoryRow)that);
    return false;
  }

  public boolean equals(HistoryRow that) {
    if (that == null)
      return false;

    boolean this_present_h_amount = true;
    boolean that_present_h_amount = true;
    if (this_present_h_amount || that_present_h_amount) {
      if (!(this_present_h_amount && that_present_h_amount))
        return false;
      if (this.h_amount != that.h_amount)
        return false;
    }

    boolean this_present_h_data = true && this.isSetH_data();
    boolean that_present_h_data = true && that.isSetH_data();
    if (this_present_h_data || that_present_h_data) {
      if (!(this_present_h_data && that_present_h_data))
        return false;
      if (!this.h_data.equals(that.h_data))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(HistoryRow other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HistoryRow typedOther = (HistoryRow)other;

    lastComparison = Boolean.valueOf(isSetH_amount()).compareTo(typedOther.isSetH_amount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetH_amount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.h_amount, typedOther.h_amount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetH_data()).compareTo(typedOther.isSetH_data());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetH_data()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.h_data, typedOther.h_data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HistoryRow(");
    boolean first = true;

    sb.append("h_amount:");
    sb.append(this.h_amount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("h_data:");
    if (this.h_data == null) {
      sb.append("null");
    } else {
      sb.append(this.h_data);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HistoryRowStandardSchemeFactory implements SchemeFactory {
    public HistoryRowStandardScheme getScheme() {
      return new HistoryRowStandardScheme();
    }
  }

  private static class HistoryRowStandardScheme extends StandardScheme<HistoryRow> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HistoryRow struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // H_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.h_amount = iprot.readDouble();
              struct.setH_amountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // H_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.h_data = iprot.readString();
              struct.setH_dataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HistoryRow struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(H_AMOUNT_FIELD_DESC);
      oprot.writeDouble(struct.h_amount);
      oprot.writeFieldEnd();
      if (struct.h_data != null) {
        oprot.writeFieldBegin(H_DATA_FIELD_DESC);
        oprot.writeString(struct.h_data);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HistoryRowTupleSchemeFactory implements SchemeFactory {
    public HistoryRowTupleScheme getScheme() {
      return new HistoryRowTupleScheme();
    }
  }

  private static class HistoryRowTupleScheme extends TupleScheme<HistoryRow> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HistoryRow struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetH_amount()) {
        optionals.set(0);
      }
      if (struct.isSetH_data()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetH_amount()) {
        oprot.writeDouble(struct.h_amount);
      }
      if (struct.isSetH_data()) {
        oprot.writeString(struct.h_data);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HistoryRow struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.h_amount = iprot.readDouble();
        struct.setH_amountIsSet(true);
      }
      if (incoming.get(1)) {
        struct.h_data = iprot.readString();
        struct.setH_dataIsSet(true);
      }
    }
  }

}

